version: "3"
services:
  database:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: challenge_hetic_list
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./mydata:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: database
      PMA_USER: user
      PMA_PASSWORD: pass
    networks:
      - mynetwork

  api:
    build: .
    restart: always
    ports:
      - 8080:3000
    working_dir: /home/node
    volumes:
      - ./:/home/node
      - /home/node/node_modules/
    environment:
      PORT: 3000
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: challenge_hetic_list
    networks:
      - mynetwork
      
networks:
  mynetwork: